### PR TITLE
add valuesFormatting by default

### LINKED ISSUE #148: Complex data types aren't supported
If submitting a bug please make sure

- [x] If you are using gdb
  - [x] `gdb --version` >= 7.7.1
  - [x] it works on the command line with `gdb`
  - [x] `cwd` and `target` are properly set

here is a list of local variables:

image

Here is a code: `std::vector<std::string> aa{"a", "bbb", ""};`

As you see `aa` isn't pretty expanded

### PR DESCRIPTION
**Pull request by WebFreak001**
by @Yanpas fix #148

### CODE REVIEW

**Comment by WebFreak001** [comment]
@Yanpas can you add it to all `configurationSnippets` and `initialConfigurations` blocks and not just to those 2 specific GDB ones?

**Comment by Yanpas** [comment]
I've amended commit

**Comment by WebFreak001** [comment]
can you also add it to the `initialConfigurations` blocks? These are the default configurations you get if you just hit that gear and select "Debug (GDB)" without any existing debug config.

**Comment by Yanpas** [comment]
done

**Pull request merged**
