### PR TITLE
#278: Add quotation marks around the variable name to support spaces

### PR DESCRIPTION
**Pull request by martin-fleck-at**

### CODE REVIEW

**Comment by WebFreak001** [comment]
just quoting them might leave quotation marks in, that will cause the parsing to fail + this behavior could change existing other MI debuggers.

I think it would be best if you can create a function that quotes variables and calls `escape` on the content only if the variables have content that needs to be quoted/escaped (spaces and special characters)

**Comment by martin-fleck-at** [comment]
@WebFreak001 Thank you for your fast reply, I really appreciate it!

I extracted the quoting into a function and use `escape` with surrounding double quotes. Escaping + double quotes is already used in several other places within the class, so I hope that is fine. For now I only do it if we encounter whitespaces which is enough for our use case but I don't know the parsing well enough to know if there are other characters that might break it as well. If you think we should check for more, please let me know.

**Comment by WebFreak001** [comment]
I changed the regex a bit but didn't actually test how it affects the debugging, can you verify if it still works as expected with your issue?

**Comment by martin-fleck-at** [comment]
@WebFreak001 I double checked with our use case and everything still works, fantastic, thank you!

**Review by WebFreak001 — APPROVED** [review]

**Pull request merged**
