### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by HenryRiley0**
1.fix  implicitly type error of LogMessage
2.fix gdb check error, checkCommand success should not warning "Configured debugger ${dbgCommand} not found"  

```
	protected checkCommand(debuggerName: string): boolean {
		try {
			const command = process.platform === 'win32' ? 'where' : 'command -v';
			execSync(`${command} ${debuggerName}`, { stdio: 'ignore' });
			return true;
		} catch (error) {
			return false;
		}
	}
```

### CODE REVIEW

**Comment by HenryRiley0** [comment]
the newest code will fail, please consider merge this pr

**Comment by GitMensch** [comment]
I'd like to pull that in, can you please add your notes to the Changelog as well?

**Comment by HenryRiley0** [comment]
> I'd like to pull that in, can you please add your notes to the Changelog as well?

ok, i will put a changelog later

**Comment by HenryRiley0** [comment]
> I'd like to pull that in, can you please add your notes to the Changelog as well?

change log added

**Pull request merged**
