### PR TITLE
Add github automated unit testing and linting.

### PR DESCRIPTION
**Pull request by brownts**
Adds CI for GitHub-based unit testing (as described in #347), as well as for linting.

Note, currently the lint job fails because there are violations in the code base.  These should likely be cleaned in the near future to avoid lint job failures going forward.

### CODE REVIEW

**Comment by GitMensch** [comment]
There's no reason to not pull this. Feel free to commit things like this (or the fix for it) directly :-)

Not sure if we can do something about the errors in the test setup?

~~~
[1670:0503/125747.120609:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

[1670:0503/125747.134172:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

[1670:0503/125748.789396:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

[1670:0503/125748.791142:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

[1670:0503/125748.903138:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

[1670:0503/125748.904863:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

[1670:0503/125749.079064:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

[1670:0503/125749.081379:ERROR:bus.cc(397)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
~~~

Additional "linting" issue not noted here #322.

**Comment by GitMensch** [comment]
Our commits possibly met a "race condition", please adjust the new file HACKING.md concerning the unit tests and its CI a bit.
Thanks.

**Comment by GitMensch** [comment]
While the linting was "copied over" and now fixed I see that [tslint is deprecated](https://github.com/palantir/tslint/issues/4534) and officially suggest to move to eslint.

Is there any reason to _not_ follow the https://code.visualstudio.com/api/advanced-topics/tslint-eslint-migration for the repo (dev dependency change/addition, rule conversion (nearly automated), CI configuration)?

**Comment by brownts** [comment]
Yes, that is correct, tslint has been deprecated for a couple years at this point.  I was planning to take a look at updating it to use the newer eslint functionality.  I hadn't looked into the automated conversion...that might be handy.  I think it would also be good to add some configuration to help identify deprecated APIs, which the current tslint configuration is not currently setup to identify.  Also, the current 'tslint.json' has a number of "recommended" rules disabled.  It would be good to get closer to the "recommended" set, with fewer exceptions.

**Comment by brownts** [comment]
I updated this now to use ESLint.  This will also check for deprecated APIs too.  I fixed the remaining deprecated API references in the code base and also a few more lint warnings that ESLint was picking up.

**Comment by GitMensch** [comment]
Thanks for abf41e475b20c4c9b27d560043cd1c1fe755e457 d6ce83cf4eeae81453f1747071df1e4b411f4b45 and db007409fad3e38cff36925897d09ab03fdaaece! I guess we can now add a single entry for "internal code cleanup using linting and CI-assisted checks", or similar to the ChangeLog :-)

Can I kindly ask you for inspecting the now existing HACKING.md and adjust the notes about testing and linting? Apart from a single changelog entry (as always a user will only see if we broke something) this is the missing part for this "area" to have it finished.

**Pull request merged**
